# Generated by Django 4.0.4 on 2022-05-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='-', verbose_name=255),
            preserve_default=False,
        ),
    ]
